# Generated by Django 2.2.1 on 2019-06-02 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_media'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='media',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
