# Generated by Django 2.2.1 on 2019-06-02 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_blog_media'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Media',
        ),
    ]
